import { useParcelKeys } from '../shared/lib/parcelKeys';
import { PageHeader } from '../widgets/PageHeader';
import { KeyGeneratorCard } from './keys/KeyGeneratorCard';
import { SavedKeysCard } from './keys/SavedKeysCard';
import styles from './KeysPage.module.css';

export function KeysPage() {
  // One instance for the whole page: useLocalStorage keeps its state per hook
  // instance, so a key generated by one card would not appear in the other's list.
  const parcelKeys = useParcelKeys();

  return (
    <div className={styles.page}>
      <PageHeader
        title="Keys"
        description="Пары RSA-ключей для шифрования посылок. Генерация идёт в браузере — приватный ключ не отправляется на сервер."
      />

      <KeyGeneratorCard addKeys={parcelKeys.addKeys} />
      <SavedKeysCard keys={parcelKeys.keys} addKey={parcelKeys.addKey} removeKey={parcelKeys.removeKey} />
    </div>
  );
}
